### ISSUE TITLE
/usr/bin/pysubs2.py doesn't work

### ISSUE THREAD

**Issue by YamashitaRen** [tkarabela/pysubs2#1]
Hi, I'm using pysubs2 on Linux and I have a problem when trying to use the pysubs2.py script.
python -m pysubs2 works fine and the .py script works fine too, if I rename it.
https://gist.github.com/YamashitaRen/5846848c372369f28431

**Comment by hpsbranco** [comment]
Yes, I was having that problem too. Fixed by removing scripts/pysubs2.py and having setuptools generate it on installation (see https://github.com/hpsbranco/pysubs2/tree/develop).

tkarabela, would take a pull request with some changes I've made? I am using pysubs2 on a small project of mine and would love to contribute to it.

**Comment by tkarabela** [comment]
Sorry for taking so long to get back to you! I was kinda busy and haven't used the library in a while. 

Anyway, I can't see your fork now @hpsbranco and I couldn't get it 100 % working myself, so I decided to drop the script for the next release (0.2.1, released today). Not the best solution, I know, but at least it's not broken anymore.

It should be trivial to replace `pysubs2.py` with a shell script, though:

```sh
#!sh
python -m pysubs2 "$@"
```
