### ISSUE TITLE
bug, when parse srt

### ISSUE THREAD

**Issue by jarodtang** [tkarabela/pysubs2#11]
Hi, 

I'm using pysubs2 to parse a existing srt file, which contains following snip. It treated 394 as text of 393. which should be two different subs with empty text.

And, it looks like subs  are better separated by "A blank line " instead of timecode's line by https://www.matroska.org/technical/specs/subtitles/srt.html

Regards,
Jarod

`
392
00:29:27,46 --> 00:29:29,83
I'm Liza Minnelli..

393
00:00:00,00 --> 00:00:00,00

394
00:00:00,00 --> 00:00:00,00
`

**Comment by tkarabela** [comment]
Thanks for the test case!

I wholeheartedly agree that "subs are better separated by a blank line", however I've seen too many SRT files with multiple subs without any blank lines inbetween to implement the parsing like that. I find multiple subtitles merged into one more annoying when viewing/editing than an occasional subtitle that contains an extra number. Parsing in the library is implemented with "best effort" goal in mind, since 100% correct parsing of files which are routinely malformed in various ways is just not possible.

In the case that the file has reasonable formatting, however, it should behave cleanly. I've fixed your issue in the newly released 0.2.3 version of the library :)
