### ISSUE TITLE
UnknownFileExtensionError not properly raised upon loading a file with unsupported format

### ISSUE THREAD

**Issue by Northurland** [tkarabela/pysubs2#85]
As title.
Python version: 3.9
pysubs2 version: 1.6.1
Operating system: Windows 10

Description:
![图片](https://github.com/tkarabela/pysubs2/assets/40388212/fc2cffb0-903e-4bbf-82fb-66ae6d5075dc)

Code above was ran in an attempt to open a file with extension .atpj (which is json-based subtitle project file for the subtitle tool ArcTime Pro; which has not an extension that is supported by pysubs2). Exception was raised at line 38 as expected, but it was a KeyError instead of UnknownFileExtensionError.

It seems that loading was done in an assumption that this json subtitle format would be similar to the type(s?) of json what the module is supposed to handle, henceforth directly loaded without looking at the extension name.

![图片](https://github.com/tkarabela/pysubs2/assets/40388212/5231010d-5bca-4898-9e2e-8254db1decc5)

**Comment by tkarabela** [comment]
Fixed in [version 1.7.0](https://pypi.org/project/pysubs2/1.7.0/).

The exception raised in this case (unrecognized content when reading the file) is FormatAutodetectionError, not UnknownFileExtensionError (that happens when saving the file, eg. `subs.save("foo.xyz")` would raise UnknownFileExtensionError).
